from dataclasses import dataclass
from enum import Enum
from mobilize.api_object import ApiObject
from mobilize.person import Person
from mobilize.event import Event
from mobilize.organization import Organization
from mobilize.referrer import Referrer
from mobilize.timeslot import Timeslot
from mobilize.custom_signup_field_value import CustomSignupFieldValue

class AttendanceStatus(Enum):
    REGISTERED = "REGISTERED"
    CANCELLED = "CANCELLED"
    CONFIRMED = "CONFIRMED"

@dataclass
class Attendance(ApiObject):
    """
    Attendance to a Mobilize event
    https://github.com/mobilizeamerica/api?tab=readme-ov-file#attendance-object
    """
    def __init__(self, **kwargs):
        args = {
            **kwargs,
            "attendance_id": self.__get_hash_id__()
        }
        super().__init__(**args)
        self.person_id = self.person.id
        self.event_id = self.event.event_id

    ## Set Directly from API Response ##
    # If the requesting organization is independent
    # and the event’s organization is coordinated, the ID omitted.
    id: int | None
    created_date: int
    modified_date: int
    person: Person
    event: Event
    timeslot: Timeslot
    sponsor: Organization
    status: AttendanceStatus
    attended: bool
    referrer: Referrer
    custom_signup_field_values: list[CustomSignupFieldValue]
    # Ignoring feedback & rating because they are not mentinoed in the API docs,
    # although they are returned by the API

    ## Injected or Generated by ETL Pipeline ##
    attendance_id: str
    person_id: int
    event_id: str