from dataclasses import dataclass
from enum import Enum
from mobilize.api_object import ApiObject
from mobilize.organization import Organization
from mobilize.timeslot import Timeslot

class EventDataVisibility(Enum):
    PUBLIC = "PUBLIC"
    PRIVATE = "PRIVATE"

class EventAccessbilityStatus(Enum):
    ACCESSIBLE = "ACCESSIBLE"
    NOT_ACCESSIBLE = "NOT_ACCESSIBLE"
    NOT_SURE = "NOT_SURE"

class EventApprovalStatus(Enum):
    APPROVED = "APPROVED"
    NEEDS_APPROVAL = "NEEDS_APPROVAL"
    REJECTED = "REJECTED"
    NEEDS_HOST_VERIFICATION = "NEEDS_HOST_VERIFICATION"

@dataclass
class Event(ApiObject):
    """
    An event managed in the Mobilize platform
    https://github.com/mobilizeamerica/api?tab=readme-ov-file#event-object
    """
    def __init__(self, **kwargs):
        args = {
            **kwargs,
            "event_id": self.__get_hash_id__()
        }
        super().__init__(**args)
    
    ## Set Directly from API Response ##
    # If the requesting organization is independent
    # and the event’s organization is coordinated, all but event_type is omitted.
    id: int | None
    title: str | None
    description: str | None
    featured_image_url: str | None
    high_priority: bool | None
    sponsor: Organization | None
    timeslots: list[Timeslot]
    #location: Location | None
    timezone: str | None
    # Defining event_type as a string rather than an enum because
    # new values may be added to the enum by the API
    event_type: str
    browser_url: str | None
    created_date: int | None
    modified_date: int | None
    visibility: EventDataVisibility | None
    address_visibility: EventDataVisibility | None
    created_by_volunteer_host: bool | None
    is_virtual: bool | None
    virtual_action_url: str | None
    #contact: Contact | None
    accessibility_status: EventAccessbilityStatus | None

    ## Injected or Generated by ETL Pipeline ##
    event_id: str